name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "20.x"
          cache: "npm"
      - run: npm ci
      - name: Run tests
        run: |
          STATUS=0
          npm test || STATUS=$?
          npm run lint -- --max-warnings=0 || STATUS=$?
          exit $STATUS
